{"name": "Параметризованный тест невалидной регистрации", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 400\n +  where 403 = <Response [403]>.status_code", "trace": "self = <test_registration_login.TestRegistrationLogin object at 0x000002503DFBD590>, invalid_data = {'name': 'Missing Email', 'password': 'pass'}\n\n    @allure.title(\"Параметризованный тест невалидной регистрации\") # По документации ожидается одно, по факту приходит другой код, баг.\n    @pytest.mark.parametrize(\"invalid_data\", TestUserData.invalid_registration_data())\n    def test_invalid_registration(self, invalid_data):\n        response = ApiClient.register_user(invalid_data)\n>       assert response.status_code == 400\nE       assert 403 == 400\nE        +  where 403 = <Response [403]>.status_code\n\ntests\\test_registration_login.py:12: AssertionError"}, "parameters": [{"name": "invalid_data", "value": "{'password': 'pass', 'name': 'Missing Email'}"}], "start": 1747331165346, "stop": 1747331165409, "uuid": "aa1b6f1a-5adb-4d53-b7e5-61214fff9a4f", "historyId": "193474feea3af555987bb2f0c6654d3f", "testCaseId": "48fbe5e48f78c2fc92b34b6bef822603", "fullName": "tests.test_registration_login.TestRegistrationLogin#test_invalid_registration", "labels": [{"name": "suite", "value": "API тесты для регистрации и авторизации"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestRegistrationLogin"}, {"name": "host", "value": "FIP-PC"}, {"name": "thread", "value": "6996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_registration_login"}]}